// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjW5xkOXKLmNT6cTmWGYAZDwWMamI2Ek0',
    appId: '1:734935401282:android:02ccbd3dfa6c98e5f27edb',
    messagingSenderId: '734935401282',
    projectId: 'apeejay-shipping-crew-app',
    storageBucket: 'apeejay-shipping-crew-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJZCuFgEzrtO7DtUjelv1xpVFdqvYP8gA',
    appId: '1:363711052423:ios:85d2eb1447a348cb459622',
    messagingSenderId: '734935401282',
    projectId: 'apeejay-shipping-crew-app',
    storageBucket: 'apeejay-shipping-crew-app.appspot.com',
    iosClientId:
        '1:734935401282:ios:842d37adb811c356f27edb',
    iosBundleId: 'com.aquarious.apeejaycrewmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJZCuFgEzrtO7DtUjelv1xpVFdqvYP8gA',
    appId: '1:363711052423:ios:85d2eb1447a348cb459622',
    messagingSenderId: '734935401282',
    projectId: 'apeejay-shipping-crew-app',
    storageBucket: 'apeejay-shipping-crew-app.appspot.com',
    iosClientId:
    '1:734935401282:ios:842d37adb811c356f27edb',
    iosBundleId: 'com.aquarious.apeejaycrewmanagement',
  );
}
